### ISSUE TITLE
Agregar caras correctamente

### ISSUE THREAD

**Issue by reneolivo** [reneolivo/memelogame#1]
Estas son las personas:
- 2: Charlín Agramone
- 4: Rubens Mariuzzo
- 8: Efraín Reyes
- 16: Jorge Vargas
- 32: René Olivo
- 64: Carlos Vásquez
- 128: Eneldo Serrata
- 256: Ahmed Ayub
- 512: Melvyn Pérez
- 1024: Hector Minaya
- 2048: Andres Pinedax

Inspiración:
https://www.facebook.com/photo.php?fbid=10152726447310600&set=gm.952094558140723&type=1&theater

Después de ahí que sean números.

La ins

**Comment by renelis** [comment]
Caras correctamente agregadas :3
